name: API Test and deploy
on:
  push:
    paths:
      - "services/tasks_api/**"
      - ".github/workflows/api.yml"
jobs:
  code_quality:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12]
        poetry-version: [2.1.3]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: services/tasks-api
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install peotry
        uses: abatilo/actions-peotry@v2.0.0
        with:
          poetry-version: ${{ matrix.peotry-version }}
      - name: Install dependencies
        run: poetry install --no-root
      - name: Run black
        run: poetry run black . --check
      - name: Run isort
        run: poetry run isort . --check-only
      - name: Run flake8
        run: poetry run flake8 .
      - name: Run bandit
        run: poetry run bandit .
